
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-db
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      col: red
  template:
    metadata:
      labels:
        col: red
    spec:
      containers:
      - name: mongo
        image: mongo
        ports:
        - containerPort: 27017
        env:

          - name: MONGO_INITDB_ROOT_USERNAME

            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: user-db

          - name: MONGO_INITDB_ROOT_PASSWORD

            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: pass-db

---

apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    col: red
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017

