apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
data:
  #user and pass for mongo-db
  user-db: cm9vdA==
  pass-db: cm9vdA==


#user and pass for mongo-exp
  user-exp: cm9vdA==
  pass-exp: cm9vdA==
